{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2024-13417",
        "assignerOrgId": "f2daf9a0-02c2-4b83-a01d-63b3b304b807",
        "state": "PUBLISHED",
        "assignerShortName": "Axis",
        "dateReserved": "2025-01-15T18:22:29.307Z",
        "datePublished": "2025-02-06T19:09:38.176Z",
        "dateUpdated": "2025-02-06T19:09:38.176Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "2N OS",
                    "vendor": "2N",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2N RFID equipped products running 2N OS 2.45 and prior"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "Specifically crafted payloads sent to the RFID reader could cause DoS of RFID reader. After the device is restarted, it gets back to fully working state."
                        }
                    ],
                    "value": "Specifically crafted payloads sent to the RFID reader could cause DoS of RFID reader. After the device is restarted, it gets back to fully working state."
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "PHYSICAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 4.6,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:P/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    },
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ]
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-248",
                            "description": "CWE-248: Uncaught Exception",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "f2daf9a0-02c2-4b83-a01d-63b3b304b807",
                "shortName": "Axis",
                "dateUpdated": "2025-02-06T19:09:38.176Z"
            },
            "references": [
                {
                    "url": "https://www.2n.com/en-GB/download/cve_2024_1341x_2nos_2_46_v1pdf"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "x_generator": {
                "engine": "Vulnogram 0.2.0"
            }
        }
    }
}