{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2024-9774",
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "state": "PUBLISHED",
        "assignerShortName": "redhat",
        "dateReserved": "2024-10-09T21:19:30.181Z",
        "datePublished": "2024-12-27T02:00:12.451Z",
        "dateUpdated": "2025-01-06T21:04:30.620Z"
    },
    "containers": {
        "cna": {
            "title": "Python-sql: python-sql unary operators does not escape non-expression",
            "metrics": [
                {
                    "other": {
                        "content": {
                            "value": "Moderate",
                            "namespace": "https://access.redhat.com/security/updates/classification/"
                        },
                        "type": "Red Hat severity rating"
                    }
                },
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "NONE",
                        "baseScore": 6.5,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "HIGH",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:N",
                        "version": "3.0"
                    },
                    "format": "CVSS"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability was found in python-sql where unary operators do not escape non-Expression."
                }
            ],
            "affected": [
                {
                    "versions": [
                        {
                            "status": "affected",
                            "version": "0",
                            "lessThan": "1.5.2",
                            "versionType": "semver"
                        }
                    ],
                    "packageName": "python-sql",
                    "collectionURL": "https://code.tryton.org/python-sql",
                    "defaultStatus": "unaffected"
                }
            ],
            "references": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2332734",
                    "name": "RHBZ#2332734",
                    "tags": [
                        "issue-tracking",
                        "x_refsource_REDHAT"
                    ]
                },
                {
                    "url": "https://discuss.tryton.org/t/security-release-for-issue-93/7889/3"
                }
            ],
            "datePublic": "2024-10-02T00:00:00+00:00",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-150",
                            "description": "Improper Neutralization of Escape, Meta, or Control Sequences",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "x_redhatCweChain": "CWE-150: Improper Neutralization of Escape, Meta, or Control Sequences",
            "timeline": [
                {
                    "lang": "en",
                    "time": "2024-12-17T03:09:08.406000+00:00",
                    "value": "Reported to Red Hat."
                },
                {
                    "lang": "en",
                    "time": "2024-10-02T00:00:00+00:00",
                    "value": "Made public."
                }
            ],
            "providerMetadata": {
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat",
                "dateUpdated": "2025-01-06T21:04:30.620Z"
            }
        },
        "adp": [
            {
                "title": "CVE Program Container",
                "references": [
                    {
                        "url": "https://lists.debian.org/debian-lts-announce/2024/10/msg00023.html"
                    }
                ],
                "providerMetadata": {
                    "orgId": "af854a3a-2127-422b-91ae-364da2661108",
                    "shortName": "CVE",
                    "dateUpdated": "2024-12-27T02:25:05.135Z"
                }
            },
            {
                "metrics": [
                    {
                        "other": {
                            "type": "ssvc",
                            "content": {
                                "timestamp": "2024-12-27T15:09:53.093177Z",
                                "id": "CVE-2024-9774",
                                "options": [
                                    {
                                        "Exploitation": "none"
                                    },
                                    {
                                        "Automatable": "no"
                                    },
                                    {
                                        "Technical Impact": "total"
                                    }
                                ],
                                "role": "CISA Coordinator",
                                "version": "2.0.3"
                            }
                        }
                    }
                ],
                "title": "CISA ADP Vulnrichment",
                "providerMetadata": {
                    "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "shortName": "CISA-ADP",
                    "dateUpdated": "2024-12-27T15:10:01.575Z"
                }
            }
        ]
    }
}