{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2024-9979",
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "state": "PUBLISHED",
        "assignerShortName": "redhat",
        "dateReserved": "2024-10-15T06:47:28.744Z",
        "datePublished": "2024-10-15T14:01:54.309Z",
        "dateUpdated": "2025-01-09T17:27:23.921Z"
    },
    "containers": {
        "cna": {
            "title": "Pyo3: risk of use-after-free in `borrowed` reads from python weak references",
            "metrics": [
                {
                    "other": {
                        "content": {
                            "value": "Moderate",
                            "namespace": "https://access.redhat.com/security/updates/classification/"
                        },
                        "type": "Red Hat severity rating"
                    }
                },
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "LOW",
                        "baseScore": 5.3,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "LOW",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
                        "version": "3.1"
                    },
                    "format": "CVSS"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in PyO3. This vulnerability causes a use-after-free issue, potentially leading to memory corruption or crashes via unsound borrowing from weak Python references."
                }
            ],
            "affected": [
                {
                    "versions": [
                        {
                            "status": "affected",
                            "version": "0.22.0",
                            "lessThan": "0.22.4",
                            "versionType": "semver"
                        }
                    ],
                    "packageName": "pyo3",
                    "collectionURL": "https://github.com/PyO3/pyo3",
                    "defaultStatus": "unaffected"
                },
                {
                    "vendor": "Red Hat",
                    "product": "Red Hat Ansible Automation Platform 2",
                    "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
                    "packageName": "python3.11-nh3",
                    "defaultStatus": "unaffected",
                    "cpes": [
                        "cpe:/a:redhat:ansible_automation_platform:2"
                    ]
                },
                {
                    "vendor": "Red Hat",
                    "product": "Red Hat Ansible Automation Platform 2",
                    "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
                    "packageName": "python3.11-rpds-py",
                    "defaultStatus": "unaffected",
                    "cpes": [
                        "cpe:/a:redhat:ansible_automation_platform:2"
                    ]
                },
                {
                    "vendor": "Red Hat",
                    "product": "Red Hat Enterprise Linux 8",
                    "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
                    "packageName": "python3.11-cryptography",
                    "defaultStatus": "unaffected",
                    "cpes": [
                        "cpe:/o:redhat:enterprise_linux:8"
                    ]
                },
                {
                    "vendor": "Red Hat",
                    "product": "Red Hat Enterprise Linux 8",
                    "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
                    "packageName": "python3.12-cryptography",
                    "defaultStatus": "unaffected",
                    "cpes": [
                        "cpe:/o:redhat:enterprise_linux:8"
                    ]
                },
                {
                    "vendor": "Red Hat",
                    "product": "Red Hat Enterprise Linux 9",
                    "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
                    "packageName": "python3.11-cryptography",
                    "defaultStatus": "unaffected",
                    "cpes": [
                        "cpe:/o:redhat:enterprise_linux:9"
                    ]
                },
                {
                    "vendor": "Red Hat",
                    "product": "Red Hat Enterprise Linux 9",
                    "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
                    "packageName": "python3.12-cryptography",
                    "defaultStatus": "unaffected",
                    "cpes": [
                        "cpe:/o:redhat:enterprise_linux:9"
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://access.redhat.com/security/cve/CVE-2024-9979",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_REDHAT"
                    ]
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2318646",
                    "name": "RHBZ#2318646",
                    "tags": [
                        "issue-tracking",
                        "x_refsource_REDHAT"
                    ]
                },
                {
                    "url": "https://crates.io/crates/pyo3"
                },
                {
                    "url": "https://github.com/PyO3/pyo3/pull/4590"
                },
                {
                    "url": "https://rustsec.org/advisories/RUSTSEC-2024-0378.html"
                }
            ],
            "datePublic": "2024-10-12T12:00:00+00:00",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-416",
                            "description": "Use After Free",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "x_redhatCweChain": "CWE-416: Use After Free",
            "workarounds": [
                {
                    "lang": "en",
                    "value": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability."
                }
            ],
            "timeline": [
                {
                    "lang": "en",
                    "time": "2024-10-14T21:01:23.698016+00:00",
                    "value": "Reported to Red Hat."
                },
                {
                    "lang": "en",
                    "time": "2024-10-12T12:00:00+00:00",
                    "value": "Made public."
                }
            ],
            "providerMetadata": {
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat",
                "dateUpdated": "2024-12-12T10:01:49.875Z"
            }
        },
        "adp": [
            {
                "metrics": [
                    {
                        "other": {
                            "type": "ssvc",
                            "content": {
                                "timestamp": "2024-10-15T14:19:04.359472Z",
                                "id": "CVE-2024-9979",
                                "options": [
                                    {
                                        "Exploitation": "none"
                                    },
                                    {
                                        "Automatable": "no"
                                    },
                                    {
                                        "Technical Impact": "partial"
                                    }
                                ],
                                "role": "CISA Coordinator",
                                "version": "2.0.3"
                            }
                        }
                    }
                ],
                "title": "CISA ADP Vulnrichment",
                "providerMetadata": {
                    "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "shortName": "CISA-ADP",
                    "dateUpdated": "2025-01-09T17:27:23.921Z"
                }
            }
        ]
    }
}